version: "3.2"

services:
  cdn:
    image: "bvphusanhaiphongcdn:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      PORT: 3001
      NODE_ENV: "production"
    ports:
      - 3001:3001
    volumes:
      - uploads:/usr/src/app/uploads

volumes:
  uploads:
    driver: local
