version: "3.2"
services:
  cdn:
    image: "registry.thinklabs.com.vn:5000/danhuongcdn:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.environment==development]
      restart_policy:
        condition: any
    environment:
      PORT: 3001
      NODE_ENV: "production"
      SERVICE_3001_NAME: "danhuongcdn"
      SERVICE_NAME: "danhuongcdn"
      SERVICE_TAGS: "danhuongcdn"
    ports:
      - target: 3001
        published: 4020
        mode: host
    volumes:
      - uploads:/usr/src/app/uploads
      - medicalreportHisSyncResource:/usr/src/app/hissync

volumes:
  uploads:
    driver: lizardfs
  medicalreportHisSyncResource:
    driver: lizardfs
