version: "3.2"
services:
  cdn:
    image: "bvhoabinhcdn:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 3001:3001
    volumes:
      - uploads:/usr/src/app/uploads

volumes:
  uploads:
    driver: local
