version: "3.2"
services:
  cdn:
    image: "registry.thinklabs.com.vn:5000/bvquoctethainguyencdn:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.environment==development]
      restart_policy:
        condition: any
    environment:
      PORT: 3001
      NODE_ENV: "production"
      SERVICE_3001_NAME: "bvquoctethainguyencdn"
      SERVICE_NAME: "bvquoctethainguyencdn"
      SERVICE_TAGS: "bvquoctethainguyencdn"
    ports:
      - target: 3001
        published: 4030
        mode: host
    volumes:
      - uploads:/usr/src/app/uploads

volumes:
  uploads:
    driver: lizardfs
