version: "3.2"

services:
  cdn:
    image: "pkmediboxcdn:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      PORT: 3001
      NODE_ENV: "production"
    ports:
      - target: 3001
        published: 3001
        mode: host
    volumes:
      - uploads:/usr/src/app/uploads

volumes:
  uploads:
    driver: local
